carla:
  host: localhost
  port: 2000
  QualityLevel: Low  # Low or Epic
  SynchronousMode: True
  SendNonPlayerAgentsInfo: True
  NumberOfVehicles: 30
  NumberOfPedestrians: 10
  WeatherId: 1

  sensors:
    camera_front:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: SceneFinal
        ImageSizeX: 320
        ImageSizeY: 240
        FOV: 90
        PositionX: 1.80
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 0

    camera_depth:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: Depth
        ImageSizeX: 320
        ImageSizeY: 240
        FOV: 90
        PositionX: 1.80
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 0

# Uncomment the following lines if you want to enable lidar publication
#    lidar_0:
#      SensorType: LIDAR_RAY_CAST
#      carla_settings:
#        Channels: 4
#        Range: 120
#        PointsPerSecond: 200000
#        RotationFrequency: 25
#        UpperFovLimit: 1.6
#        LowerFovLimit: -1.6
#        PositionX: 0.0
#        PositionY: 0
#        PositionZ: 1.50
#        RotationPitch: 0
#        RotationYaw: 0
#        RotationRoll: 0
